#!/bin/bash

# get the path of the current script
SHELL_FOLDER=$(dirname $(readlink -f "$0"))

CLASSPATH="classes:lib/colt.jar:lib/lingpipe-3.4.0.jar:lib/MinCutSeg.jar:lib/mtj.jar:lib/options.jar:lib/log4j-1.2.14.jar"

#java -cp ${CLASSPATH} edu.mit.nlp.segmenter.SegTester -config $1 -debug
java -Duser.dir=${SHELL_FOLDER} -cp ${CLASSPATH} edu.mit.nlp.segmenter.SegTester -config $1 -num-segs 7
#java -cp ${CLASSPATH} edu.mit.nlp.segmenter.SegTester -config $1
